#!/bin/sh

passFile=$1
passphrase=$2
passwordLocation=$3
encryptedFileName=$4

gpg -c --batch --passphrase ${passphrase} -o ${passwordLocation}/${encryptedFileName} ${passwordLocation}/${passFile}
if [[ $? -ne 0 ]]
then
  echo "Password encryption failed"
  exit 1
else
  echo "Encrypted password file created : ${passwordLocation}/${encryptedFileName}"
fi


## For decryption
extension=
gpg -d -q --batch --passphrase ${passwordLocation}/${encryptedFileName}
