#!/bin/sh

workingDir=$1
targetDir=$2
userInputFileName=$3
finalFileSize=$4
choiceOfName1=$5
choiceOfName2=$6

fileName=combinedFile_${choiceOfName1}_${choiceOfName2}.csv

##################################################################
############### Splitting files based on Size & Renaming #########

## Function for merge-split-rename files
fn_merge_files_based_on_size()
{
dir=$1
finalFileSize=$2
fileName=$3

## Traverse through files > 0 byte and merge the contents to one single file
## -maxdepth 1 --> If the program shouldn't pick up directories inside ${dir}
## $files =~ \.t?gz$ --> If there are zipped files that can't be read by cat

for files in `find ${dir}/ -maxdepth 1 -size +0c -type f`
do
        if [[ -e $files && $files =~ \.t?gz$ ]]
        then
                cat $files >> ${workingDir}/${fileName}
        else
                echo "Corrupt Files"
                exit 1
        fi
done

## Split files based on size
## Splitting won't break lines
## Additional suffixes added in the end (before extension) are numeric. Extension is csv.
## "choiceOfName1 & 2" are just file names; they could be ommitted/replaced with user choice names
cd ${workingDir}
split --line-bytes=${finalFileSize} ${fileName} --numeric-suffixes -e --additional-suffix=.csv ${userInputFileName}_${choiceOfName1}_${choiceOfName2}_
}

fn_merge_files_based_on_size ${workingDir} ${finalFileSize} ${fileName}

# zip files
for i in `ls -pL ${workingDir}/ | grep -v gz | grep -v ${fileName}`
do
gzip --fast ${workingDir}/${i}
done

# Move files
for i in `ls -pL ${workingDir} | grep -v / | grep -v ${fileName}`
do
mv ${workingDir}/${i} ${targetDir}/${i}
done

# Remove temporary files created
rm -f ${workingDir}/${fileName}
